name: chat_app_secure
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  dio: ^5.7.0
  email_validator: ^3.0.0
  hooks_riverpod: ^2.6.1
  socket_io_client: ^3.0.2
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.4.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

fonts:
  - family: Rubik
    fonts:
      - asset: assets/fonts/Rubik-Regular.ttf
        weight: 400
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 700
  - family: Agbalumo
    fonts:
      - asset: assets/fonts/Agbalumo-Regular.ttf
        weight: 400
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Manrope-Bold.ttf
        weight: 700
      - asset: assets/fonts/Manrope-ExtraBold.ttf
        weight: 600
      - asset: assets/fonts/Manrope-ExtraLight.ttf
        weight: 500
      - asset: assets/fonts/Manrope-Regular.ttf
        weight: 400
      - asset: assets/fonts/Manrope-Light.ttf
        weight: 300
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 700
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - assets: assets/fonts/Nunito-Light.ttf
        weight: 300
      - assets: assets/fonts/Nunito-Light.ttf
        weight: 200
