// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoNG_8zWEjMZ3R1TaTP9v0D5MjTWyO30',
    appId: '1:732766551957:web:21058380d52f4a347e409c',
    messagingSenderId: '732766551957',
    projectId: 'chatting-secure-app',
    authDomain: 'chatting--app-7007e.firebaseapp.com',
    storageBucket: 'chatting-secure-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTNYlLvdi90TRokee8W8O90OxuU1aiDY',
    appId: '1:732766551957:android:8ccb78f8691a21587e409c',
    messagingSenderId: '732766551957',
    projectId: 'chatting-secure-app',
    storageBucket: 'chatting-secure-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTaNXr1SWlBlqkx-7JC9aNUlU4yp3mzo',
    appId: '1:732766551957:ios:21db81f550054cd87e409c',
    messagingSenderId: '732766551957',
    projectId: 'chatting-secure-app',
    storageBucket: 'chatting-secure-app.firebasestorage.app',
    iosBundleId: 'com.example.chatAppSecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaTaNXr1SWlBlqkx-7JC9aNUlU4yp3mzo',
    appId: '1:732766551957:ios:21db81f550054cd87e409c',
    messagingSenderId: '732766551957',
    projectId: 'chatting-secure-app',
    storageBucket: 'chatting-secure-app.firebasestorage.app',
    iosBundleId: 'com.example.chatAppSecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVoNG_8zWEjMZ3R1TaTP9v0D5MjTWyO30',
    appId: '1:732766551957:web:b66d70cd901da92b7e409c',
    messagingSenderId: '732766551957',
    projectId: 'chatting-secure-app',
    authDomain: 'chatting--app-7007e.firebaseapp.com',
    storageBucket: 'chatting-secure-app.firebasestorage.app',
  );

}